apiVersion: v1
kind: ConfigMap
metadata:
  name: dark-factory-config
  labels:
    app: dark-factory
    app.kubernetes.io/name: dark-factory
data:
  JUDGE_BACKEND_MODE: "stub"
  SAGEMAKER_ENDPOINT_NAME: "judge-01-scenario-eval"
  AWS_DEFAULT_REGION: "us-west-2"
  DTU_BASE_URL: ""
  JUDGE_URL: "http://dark-factory.staging.svc.cluster.local:8080"
  SCENARIO_EXECUTOR_URL: "http://dark-factory.staging.svc.cluster.local:8080"
  DTU_K8S_ENABLED: "false"
