apiVersion: v1
kind: Service
metadata:
  name: dark-factory
  labels:
    app: dark-factory
    app.kubernetes.io/name: dark-factory
    app.kubernetes.io/part-of: dark-factory
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: dark-factory
